#!/bin/bash

echo "🚀 Configuração do MarketX Lite para Neon + Vercel"
echo "================================================"
echo ""

echo "📋 Passos para configurar:"
echo ""
echo "1️⃣  Criar conta no Neon (https://neon.tech)"
echo "   - Faça login com GitHub"
echo "   - Crie um novo projeto PostgreSQL"
echo "   - Copie a CONNECTION STRING"
echo ""
echo "2️⃣  Configurar Environment Variables na Vercel:"
echo "   - Vá para o projeto no painel Vercel"
echo "   - Settings → Environment Variables"
echo "   - Adicione as seguintes variáveis:"
echo ""
echo "   DATABASE_URL=postgresql://user:password@ep-xxx.us-east-1.aws.neon.tech/dbname?sslmode=require"
echo "   NEXTAUTH_SECRET=seu-segredo-unico-com-pelo-menos-32-caracteres"
echo "   NEXTAUTH_URL=https://kalshi10.vercel.app"
echo ""
echo "3️⃣  Deploy automático:"
echo "   - Faça push das mudanças para o GitHub"
echo "   - Vercel detectará e fará deploy automático"
echo "   - O Prisma criará as tabelas automaticamente"
echo ""
echo "🔐 Credenciais de Acesso:"
echo "   Admin: admin@marketx.com / admin123"
echo "   User:  user@test.com / user123"
echo ""
echo "📊 URLs após deploy:"
echo "   Login: https://kalshi10.vercel.app/login"
echo "   Admin: https://kalshi10.vercel.app/admin"
echo "   API:  https://kalshi10.vercel.app/api/test"
echo ""
echo "⚠️  Importante:"
echo "   - Use a CONNECTION STRING completa do Neon"
echo "   - Inclua ?sslmode=require no final da URL"
echo "   - O NEXTAUTH_SECRET deve ser único e secreto"
echo "   - O NEXTAUTH_URL deve ser a URL completa do seu site"
echo ""
echo "✅  Após configurar, o sistema criará as tabelas automaticamente!"